ptcFilePaths = { '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000016.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000017.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000018.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000019.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000020.pcd'; ...
     '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000021.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000022.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000023.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000024.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000025.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000026.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000027.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000028.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000029.pcd'; ...
    '/home/jc/Documents/stereo-lidar-calibration/exclude_dir/robosense_points/000030.pcd';
    };
for i = 1:15
    ptCloud = pcread(ptcFilePaths{i});
    locations = ptCloud.Location;
    locations = reshape(locations,1,[],3);
    a = all(~isnan(locations),3);

    locations = locations(:,all(~isnan(locations),3),:);
    ptCloudXYZ = pointCloud(locations);
    id = num2str(i+15,'%06d');
    pcwrite(ptCloudXYZ,"pointCloud/"+id+".pcd",'Encoding','binary')
end

